import React from 'react'
import Head from 'next/head'

function MetaHead() {
  return (
    <Head>
    <title>Your Store</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  )
}

export default MetaHead