import React from 'react'
import Head from 'next/head'

function MetaHead() {
  return (
    <Head>
    <title>nuevos Porcelanatos</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="title" content="novo Porcelanato"/>
<meta name="description" content="Somos novo Porcelanato, la mejor elección para tu hogar."/>
<meta name="keywords" content="novo porcelanatos, porcelanatos, novo, porcelanatos, ceramicas, sanitarios, pisos, griferias"/>
<meta name="robots" content="index, follow"/>
<meta httpEquiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="language" content="Spanish"/>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
<link rel="manifest" href="/site.webmanifest"/>
  </Head>
  )
}

export default MetaHead